name: Process Data
on: workflow_dispatch
#  schedule:
#    - cron: '0 0 * * *' # At 00:00 (midnight) every day

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r xml2json/requirements.txt

      - name: Download zip file
        run: wget -O switchtdb.zip https://www.gametdb.com/switchtdb.zip

      - name: Extract XML file
        run: unzip -qq switchtdb.zip

      - name: Checkout repo content again
        uses: actions/checkout@v2

#      - name: Execute Python script
#        run: |
#          cp xml2json/xml2json.py xml2json.py
#          python xml2json.py

      - name: Replace Game Data
        run: | 
          rm gamelist/gdata.json
          cp gdata.json gamelist/gdata.json

      - name: Delete Extra Files
        run: |
          rm switchtdb.zip
          rm switchtdb.xml
          rm xml2json.py
          rm gdata.json
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated db" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflow-test