name: Process Data
on: workflow_dispatch
#  schedule:
#    - cron: '0 0 * * *' # At 00:00 (midnight) every day

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Choose the Python version you need
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r xml2json/requirements.txt

#      - name: Download zip file
#        run: wget -O xml2json/switchtdb.zip https://www.gametdb.com/switchtdb.zip

#      - name: Extract XML file
#        id: unzip  
#        run: unzip -qq xml2json/switchtdb.zip -d xml2json

#      - name: Checkout repo content again
#        uses: actions/checkout@v2

      - name: Execute Python script
        id: script
        run: |
          cp xml2json/xml2json.py xml2json.py
          python xml2json.py
#         COPY xml2json/xml2json.py /usr/bin/xml2json.py
#         python /usr/bin/xml2json.py
#          python xml2json.py

#      - name: Delete Files
#        if: steps.script.outcome == 'success'
#        run: |
#          rm xml2json/switchtdb.zip
#          rm xml2json/switchtdb.xml

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated db" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflow-test